server:
  port: 8081
spring:
  application:
    name: auth-service
  config:
    import: "optional:classpath:application-common.yml"
  datasource:
    # Get this URL from Neon: Dashboard -> Connection String -> JDBC
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update # Automatically creates tables on first run
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        # Neon works best when you don't hold connections open too long
        jdbc:
          batch_size: 10
  cloud:
    gateway:
      routes:
        - id: auth-service-swagger
          uri: lb://auth-service
          predicates:
            - Path=/auth/v3/api-docs/**