server:
  port: 10000
  forward-headers-strategy: framework
spring:
  application:
    name: auth-service
  config:
    import: "optional:classpath:application-common.yml"
  datasource:
    # Get this URL from Neon: Dashboard -> Connection String -> JDBC
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update # Automatically creates tables on first run
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        # Neon works best when you don't hold connections open too long
        jdbc:
          batch_size: 10

management:
  endpoints:
    web:
      exposure:
        include: health
      base-path: /actuator # Ensure this is explicit
  endpoint:
    health:
      show-details: always  # Reveals the 'db' component
      show-components: always
  # This tells Spring NOT to treat actuator as a static resource
  server:
    add-application-context-header: false

springdoc:
  # Set this to FALSE to stop the automatic 3-endpoint injection
  show-actuator: false
  api-docs:
    path: /v3/api-docs
    groups:
      enabled: true
  swagger-ui:
    use-root-path: false
