services:
  # Service 1: The Auth Service
  - type: web
    name: auth-service
    runtime: docker
    dockerContext: .
    dockerfilePath: auth-service/auth.Dockerfile # Point to a specific Dockerfile
    plan: free
    envVars:
      - key: PORT
        value: 8081
      - key: SPRING_PROFILES_ACTIVE
        value: prod

  # Service 2: The Gateway Service
  - type: web
    name: gateway-service
    runtime: docker
    dockerContext: .
    dockerfilePath: gateway-service/gateway.Dockerfile
    plan: free
    envVars:
      - key: PORT
        value: 8080
      - key: AUTH_SERVICE_URL
        value: http://auth-service:8081 # Internal networking