spring:
  application:
    name: gateway-service
  config:
    import: "optional:classpath:application-common.yml" # Imports shared logging levels

  cloud:
    gateway:
      routes:
        - id: auth-public
          uri: http://localhost:8081
          predicates:
            - Path=/auth/register,/auth/token,/auth/validate

        - id: auth-protected
          uri: http://localhost:8081
          predicates:
            - Path=/auth/me
          filters:
            - AuthenticationFilter

jwt:
  secret: 5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437