spring:
  main:
    web-application-type: reactive
  application:
    name: gateway-service
  config:
    import: "optional:classpath:application-common.yml" # Imports shared logging levels

  cloud:
    gateway:
      routes:
        - id: auth-public
          uri: ${AUTH_SERVICE_URL:http://localhost:8081}
          predicates:
            - Path=/auth/register,/auth/token,/auth/validate

        - id: auth-protected
          uri: ${AUTH_SERVICE_URL:http://localhost:8081}
          predicates:
            - Path=/auth/me
          filters:
            - AuthenticationFilter
        # Route for the Auth Service API documentation
        - id: auth-api-docs
          uri: ${AUTH_SERVICE_URL:http://localhost:8081}
          predicates:
            - Path=/auth/v3/api-docs/**
          filters:
            - RewritePath=/auth/(?<path>.*), /$\{path}

        # Route for actual Auth Service functional endpoints
        - id: auth-service
          uri: ${AUTH_SERVICE_URL:http://localhost:8081}
          predicates:
            - Path=/auth/**
          filters:
            - RewritePath=/auth/(?<path>.*), /$\{path}

springdoc:
  swagger-ui:
    # This creates the dropdown menu in the top right of Swagger
    urls:
      - name: Auth Service
        url: /auth/v3/api-docs
      - name: Gateway Service
        url: /v3/api-docs

management:
  endpoints:
    web:
      exposure:
        include: health
      base-path: /actuator
  endpoint:
    health:
      show-details: always
      show-components: always